snapshots:
  - name: products_snapshot
    relation: source('landing', 'products')
    config:
      schema: bronze
      unique_key: id
      strategy: timestamp
      updated_at: created_at
      dbt_valid_to_current: "to_date('9999-12-31')"
    columns:
      - name: id
        tests:
          - unique:
              config:
                where: "dbt_valid_to = to_date('9999-12-31')"
      - name: category
        tests:
          - unique:
              config:
                warn_if: ">1"
                error_if: ">4"
